### ISSUE TITLE
[Question] What is the best way to interpolate LST for cloudy pixels?

### ISSUE THREAD

**Issue by mwussow** [sofiaermida/Landsat_SMW_LST#2]
Dear Ms. Ermida,

thank you for your great LST algorithm - very helpful!
I am wondering what is the best method to interpolate LST values for cloudy pixels. 
In your `example_1.js`, you select the first image from the collection with `var exImage = LandsatColl.first();`. The resulting image only includes unmasked pixels, i.e., non-cloudy observations.

I would like to **interpolate the values of cloudy pixels** in a given image, **based on the observed dynamics across the entire image collection**. Ideally, I would like to interpolate the full time series for each pixel. 
Do you know of an algorithm (ideally ready-to-use), that imputes missing values in a given image based on the variation observed in the entire date range?

Thanks in advance!

**Comment by sofiaermida** [comment]
Hi!

Thank you for the interest.

Infrared sensors cannot be used to estimate LST under cloudy pixels. The result would return the cloud temperature and not the surface temperature. I do not recomend interpolating the LST values over cloudy areas since the cloud completely changes the radiative balance at the surface (you might have noticed the the temperature under a cloud is not the same as under direct sunlight). I know such methods exist but they will not provide a realistic LST expected under cloud cover.

If you need more complete fields you can try doing composites over a given period (e.g. a monthly mean).
